### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by MakMuftic**
:robot: I have created a release *beep* *boop*
---

<details><summary>node-template: 4.0.3-dev</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * node-template-runtime bumped from 4.0.2-dev to 4.0.3-dev
</details>

<details><summary>node-template-runtime: 4.0.3-dev</summary>

### Dependencies

</details>

<details><summary>sygma-basic-feehandler: 0.3.0</summary>

### Features

* Remove BridgeCommitteeOrigin from some pallets' config ([#104](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/104)) ([abfe1ff](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/abfe1ffdf1d992d33be4cad9374bd5be92b87343))
</details>

<details><summary>sygma-bridge: 0.3.0</summary>

### Features

* Remove BridgeCommitteeOrigin from some pallets' config ([#104](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/104)) ([abfe1ff](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/abfe1ffdf1d992d33be4cad9374bd5be92b87343))
</details>

<details><summary>sygma-fee-handler-router: 0.3.0</summary>

### Features

* Remove BridgeCommitteeOrigin from some pallets' config ([#104](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/104)) ([abfe1ff](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/abfe1ffdf1d992d33be4cad9374bd5be92b87343))
</details>

<details><summary>sygma-rpc: 0.2.1</summary>

### Dependencies

</details>

<details><summary>sygma-runtime-api: 0.2.1</summary>

### Dependencies

</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by tolak — APPROVED** [review]

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-basic-feehandler-v0.3.0 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-bridge-v0.3.0 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-fee-handler-router-v0.3.0 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-rpc-v0.2.1 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-runtime-api-v0.2.1 :sunflower:

**Pull request merged**
