### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by MakMuftic**
:robot: I have created a release *beep* *boop*
---

<details><summary>node-template: 4.0.2-dev</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * node-template-runtime bumped from 4.0.1-dev to 4.0.2-dev
</details>

<details><summary>node-template-runtime: 4.0.2-dev</summary>

### Dependencies

</details>

<details><summary>sygma-access-segregator: 0.2.0</summary>

### Features

* Upgrade to Polkadot v0.9.39 ([#85](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/85)) ([d964bc6](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d964bc607c2c5c5bb9436fa07262977c19ebbaa4))
* Upgrade to Polkadot v0.9.40 ([#87](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/87)) ([db11298](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/db11298c91f65d52c9b6eeab0e7757ca49bf77ff))
* Upgrade to polkadot v0.9.42 ([#101](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/101)) ([6651e31](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/6651e31e9f98f6ca07cfd3be482963c3281d68cc))

### Bug Fixes

* avoid without storage info macro ([#99](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/99)) ([abd6db1](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/abd6db1c00940de65a71a50232962bc943e0aa39))
* Set extrinsic weight based on benchmarking ([#100](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/100)) ([d52594c](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d52594caecdd95ef9e259e1b31dc340d9059d41e))
</details>

<details><summary>sygma-basic-feehandler: 0.2.0</summary>

### Features

* Upgrade to Polkadot v0.9.39 ([#85](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/85)) ([d964bc6](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d964bc607c2c5c5bb9436fa07262977c19ebbaa4))
* Upgrade to Polkadot v0.9.40 ([#87](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/87)) ([db11298](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/db11298c91f65d52c9b6eeab0e7757ca49bf77ff))
* Upgrade to polkadot v0.9.42 ([#101](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/101)) ([6651e31](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/6651e31e9f98f6ca07cfd3be482963c3281d68cc))

### Bug Fixes

* avoid without storage info macro ([#99](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/99)) ([abd6db1](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/abd6db1c00940de65a71a50232962bc943e0aa39))
* Set extrinsic weight based on benchmarking ([#100](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/100)) ([d52594c](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d52594caecdd95ef9e259e1b31dc340d9059d41e))
</details>

<details><summary>sygma-bridge: 0.2.0</summary>

### Features

* Separate MPC address setup logic from other admin extrinsics ([#82](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/82)) ([1590c91](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/1590c91d84b2e5fa92650ae8bc5b23162dfd6f99))
* Upgrade to Polkadot v0.9.39 ([#85](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/85)) ([d964bc6](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d964bc607c2c5c5bb9436fa07262977c19ebbaa4))
* Upgrade to Polkadot v0.9.40 ([#87](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/87)) ([db11298](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/db11298c91f65d52c9b6eeab0e7757ca49bf77ff))
* Upgrade to polkadot v0.9.42 ([#101](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/101)) ([6651e31](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/6651e31e9f98f6ca07cfd3be482963c3281d68cc))

### Bug Fixes

* add overflow checks ([#96](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/96)) ([2255492](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/2255492150d523277034dd2646cae900b6f7e4b4))
* avoid panic with invalid proposal data ([#97](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/97)) ([c3b7da7](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/c3b7da77459023ac2b8ce3a83b9c24b74a80a004))
* avoid without storage info macro ([#99](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/99)) ([abd6db1](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/abd6db1c00940de65a71a50232962bc943e0aa39))
* Set extrinsic weight based on benchmarking ([#100](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/100)) ([d52594c](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d52594caecdd95ef9e259e1b31dc340d9059d41e))
</details>

<details><summary>sygma-fee-handler-router: 0.2.0</summary>

### Features

* Upgrade to Polkadot v0.9.39 ([#85](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/85)) ([d964bc6](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d964bc607c2c5c5bb9436fa07262977c19ebbaa4))
* Upgrade to Polkadot v0.9.40 ([#87](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/87)) ([db11298](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/db11298c91f65d52c9b6eeab0e7757ca49bf77ff))
* Upgrade to polkadot v0.9.42 ([#101](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/101)) ([6651e31](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/6651e31e9f98f6ca07cfd3be482963c3281d68cc))

### Bug Fixes

* avoid without storage info macro ([#99](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/99)) ([abd6db1](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/abd6db1c00940de65a71a50232962bc943e0aa39))
* Set extrinsic weight based on benchmarking ([#100](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/100)) ([d52594c](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d52594caecdd95ef9e259e1b31dc340d9059d41e))
</details>

<details><summary>sygma-rpc: 0.2.0</summary>

### Features

* Upgrade to Polkadot v0.9.39 ([#85](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/85)) ([d964bc6](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d964bc607c2c5c5bb9436fa07262977c19ebbaa4))
* Upgrade to Polkadot v0.9.40 ([#87](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/87)) ([db11298](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/db11298c91f65d52c9b6eeab0e7757ca49bf77ff))
* Upgrade to polkadot v0.9.42 ([#101](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/101)) ([6651e31](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/6651e31e9f98f6ca07cfd3be482963c3281d68cc))
</details>

<details><summary>sygma-runtime-api: 0.2.0</summary>

### Features

* Upgrade to Polkadot v0.9.39 ([#85](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/85)) ([d964bc6](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d964bc607c2c5c5bb9436fa07262977c19ebbaa4))
* Upgrade to Polkadot v0.9.40 ([#87](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/87)) ([db11298](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/db11298c91f65d52c9b6eeab0e7757ca49bf77ff))
* Upgrade to polkadot v0.9.42 ([#101](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/101)) ([6651e31](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/6651e31e9f98f6ca07cfd3be482963c3281d68cc))
</details>

<details><summary>sygma-traits: 0.2.0</summary>

### Features

* Upgrade to Polkadot v0.9.39 ([#85](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/85)) ([d964bc6](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/d964bc607c2c5c5bb9436fa07262977c19ebbaa4))
* Upgrade to Polkadot v0.9.40 ([#87](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/87)) ([db11298](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/db11298c91f65d52c9b6eeab0e7757ca49bf77ff))
* Upgrade to polkadot v0.9.42 ([#101](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/101)) ([6651e31](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/6651e31e9f98f6ca07cfd3be482963c3281d68cc))

### Bug Fixes

* avoid without storage info macro ([#99](https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/99)) ([abd6db1](https://github.com/sygmaprotocol/sygma-substrate-pallets/commit/abd6db1c00940de65a71a50232962bc943e0aa39))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by mpetrun5 — APPROVED** [review]

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-access-segregator-v0.2.0 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-basic-feehandler-v0.2.0 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-bridge-v0.2.0 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-fee-handler-router-v0.2.0 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-rpc-v0.2.0 :sunflower:

**Comment by MakMuftic** [comment]
:robot: Release is at https://github.com/sygmaprotocol/sygma-substrate-pallets/releases/tag/sygma-traits-v0.2.0 :sunflower:

**Pull request merged**
